accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

apartment/apts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'apts'
urlpatterns=[
    path('',views.home,name='home'),
    path('search/', views.searchform, name='searchform'),
]

apts/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url

app_name = 'apts'
urlpatterns=[
    path('',views.home,name='home'),
    path('search/', views.searchform, name='searchform'),
    url(r'(?P<id>\d+)/fav_post/$',views.fav_post,name='fav_post'),
    url(r'(?P<id>\d+)/favorites/', views.favorites, name='favorites'),
    path('dirfav/', views.dirfav, name='dirfav'),
    path('listings/',include('listings.urls')),
]

listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index),
    path('listingfun', views.listingfun,name='listingfun'),
    path('apt/<listing_title>', views.listinggo,name='listinggo'),
    path('search', views.search, name='search'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from apartment import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apts.urls')),
    path('accounts/',include('accounts.urls')),
    path('listings/',include('listings.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apts/models.py
from django.db import models

# Create your models here.

apartment/accounts/views.py
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth
# Create your views here.

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect("/")
        else:
            messages.info(request,'Invalid credentials')
            return redirect('/accounts/login')

    else:
        return render(request,'apts/login.html')

def register(request):
    if request.method=='POST':
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        username=request.POST['username']
        email=request.POST['email']
        password1=request.POST['password1']

        if User.objects.filter(username=username).exists():
            messages.info(request,'Username taken')
            return redirect('/accounts/register')
        else:
            user = User.objects.create_user(username=username,password=password1,email=email, first_name=first_name, last_name=last_name)
            user.save()
            return redirect('/accounts/login')
        
    else:
        return render(request,'apts/register.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

apartment/apts/views.py
from django.db import models
from django.db.models import Q
from django.shortcuts import render, redirect
from listings import models
from apts.filters import AptFilter
# from .choices import price_choices, bedroom_choices, state_choices

# Create your views here.

def home(request):

    rep1 = models.Listing.objects.all()
    context={
        'listings':rep1
    }
    return render(request, 'apts/home.html',context)


# def searchform(request):
#     qs = models.Listing.objects.all()
#     filt= AptFilter(request.GET,queryset=qs)
#     print ("hiii\nhiiii\nhiiiii\nhiiii")
#     context ={
#       'filter':filt
#     }
#     print(filt.qs)
#     return render(request, "apts/searchflat.html",context)

def searchform(request):
    rooms = request.GET.get('bedroom', None)
    price = request.GET.get('rent', None)
    city = request.GET.get('city', None)

    print(rooms,price,city)

    apartments = models.Listing.objects.all()
    q1=Q(price__lte=price) 
    q2=Q(bedrooms=rooms)
    q3=Q(city=city)
    print(q1,q2,q3 ,"queryyyyy")
    qs=apartments.filter(q1 & q2 & q3)
    print(qs)
    
    print("hiiiiiiiiiiiii\n",qs)
    context ={
      'filter':qs
    }
    return render(request, "apts/searchflat.html",context)

apts/views.py
from django.db import models
from django.db.models import Q
from django.shortcuts import render, redirect
from listings import models
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth

# Create your views here.

def home(request):

    rep1 = models.Listing.objects.order_by('-list_date')[0:3]
    context={
        'listings':rep1
    }
    return render(request, 'apts/home.html',context)

def fav_post(request,id):  #------------------------add/ remove post
    post=get_object_or_404(models.Listing,id=request.GET.get('post_id'))
    if post.fav.filter(id=request.user.id).exists():
        post.fav.remove(request.user)                 
    else:
        post.fav.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())

def favorites(request,id): #---------------------handles button display
    listing = models.Listing.objects.all()
    print("id",id)
    is_fav= False     
    post=get_object_or_404(models.Listing,id=id)
    if post.fav.filter(id=request.user.id).exists():
        is_fav=True
        # context = {
        #   'listing': listing,
        #       'fav_post':is_fav,
        #      }
        # return render(request, 'apts/showflat.html', context)
    user=request.user
    fav_post=user.fav.all()
    return render(request,'accounts/fav.html',{'fav_post':fav_post})

def dirfav(request):  
    user=request.user
    fav_post=user.fav.all()
    return render(request,'accounts/fav.html',{'fav_post':fav_post})



def searchform(request):
    queryset_list = models.Listing.objects.order_by('-list_date')

    if 'bedroom' in request.GET:
        bed = request.GET['bedroom']
        if bed:
          queryset_list = queryset_list.filter(bedrooms=bed)

    if 'rent' in request.GET:
        price = request.GET['rent']
        print("------------------------------------")
        print("------------------------------------")
        print("------------------------------------")
        print("------------------------------------")
        print("------------------------------------")
        print(price,type(price))
        if price:
          price = int(request.GET['rent'])
          queryset_list = queryset_list.filter(price__lte=price)
          print(price)

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
          queryset_list = queryset_list.filter(city=city)
   
    furniture=request.GET.get('furnished')
    parking_lot=request.GET.get('parking')

    if furniture == 'on':
        furniture = True
        q4=Q(is_furnished= furniture)
        q6=Q(is_furnished= furniture)
    else:
        furniture = False
        q4=Q(is_furnished= furniture)
        furniture = True
        q6=Q(is_furnished= furniture)

    if parking_lot == 'on':
        parking_lot = True
        q5=Q(park_lot=parking_lot)
        q7=Q(park_lot=parking_lot)
    else:
        parking_lot = False
        q5=Q(park_lot=parking_lot)
        parking_lot = True
        q7=Q(park_lot=parking_lot)
    
    
        
    queryset_list=queryset_list.filter(q5 | q7)
    queryset_list=queryset_list.filter(q4 | q6)
    print("hiiiiiiiiiiiii\n",q4,q5,q6)
    context ={
      'filter':queryset_list
    }
    return render(request, "apts/searchflat.html",context)

apts/templates/accounts/fav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="fontawesome-5.5/css/all.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.5.0/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/bootstrap.min.css" />
  <link rel="stylesheet" href="../static/css/home.css" />
  <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
  <title>Document</title>
</head>

<body>
  <nav class="navbar navbar-expand-md tm-navbar" id="tmNav">              
    <div class="container">   
      <div class="tm-next">
        <a href="{% url 'apts:home' %}" class="navbar-brand"> <p style='color:blue'> <i class="fa fa-home" aria-hidden="true"></i>  GHARDEKHO </p></a>
      </div>             
              
    </div>
  </nav>



  <!-- Listings -->
  <section id="listings" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Your Favorite Listings</h3>
      <div class="row">
        {% if fav_post %}
        {% for apts in fav_post %}
        <!-- Listing 1 -->
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" style="height: 200px;" src="{{ apts.photo_main.url }}" alt="">
            <div class="card-body">
              <div class="listing-heading text-center">
               <p><a class="card-title" href="{% url 'listings:listinggo' apts.title %}" >{{ apts.title }}</a></p>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i> {{ apts.city }}, {{ apts.zipcode }}
                </p>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-bed"></i> Bedrooms: {{ apts.bedrooms }}
                </div>
                <div class="col-6">
                  <i class="fas fa-bath"></i> Bathrooms: {{ apts.bathrooms }}
                </div>
              </div>
              <hr>
              <div class="row text-secondary pb-2">
                <div class="col-9">
                  <i class="fas fa-clock"></i> {{ apts.list_date | timesince }}
                </div>
                <form action="{% url 'apts:fav_post' id=apts.id %}" method="GET">
                    <button type="submit" name="post_id" value="{{ apts.id }}" class="btn btn-danger">Remove from favorites</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
          <p>No Listings Available</p>
        </div>
        {% endif %}
</div></div>
  </section>

  <script src="js/jquery-1.9.1.min.js"></script>
  <script src="slick/slick.min.js"></script>
  <script src="magnific-popup/jquery.magnific-popup.min.js"></script>
  <script src="js/easing.min.js"></script>
  <script src="js/jquery.singlePageNav.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script>

    function getOffSet() {
      var _offset = 450;
      var windowHeight = window.innerHeight;

      if (windowHeight > 500) {
        _offset = 400;
      }
      if (windowHeight > 680) {
        _offset = 300
      }
      if (windowHeight > 830) {
        _offset = 210;
      }

      return _offset;
    }

    function setParallaxPosition($doc, multiplier, $object) {
      var offset = getOffSet();
      var from_top = $doc.scrollTop(),
        bg_css = 'center ' + (multiplier * from_top - offset) + 'px';
      $object.css({ "background-position": bg_css });
    }

    // Parallax function
    // Adapted based on https://codepen.io/roborich/pen/wpAsm        
    var background_image_parallax = function ($object, multiplier, forceSet) {
      multiplier = typeof multiplier !== 'undefined' ? multiplier : 0.5;
      multiplier = 1 - multiplier;
      var $doc = $(document);
      // $object.css({"background-attatchment" : "fixed"});

      if (forceSet) {
        setParallaxPosition($doc, multiplier, $object);
      } else {
        $(window).scroll(function () {
          setParallaxPosition($doc, multiplier, $object);
        });
      }
    };

    var background_image_parallax_2 = function ($object, multiplier) {
      multiplier = typeof multiplier !== 'undefined' ? multiplier : 0.5;
      multiplier = 1 - multiplier;
      var $doc = $(document);
      $object.css({ "background-attachment": "fixed" });

      $(window).scroll(function () {
        if ($(window).width() > 768) {
          var firstTop = $object.offset().top,
            pos = $(window).scrollTop(),
            yPos = Math.round((multiplier * (firstTop - pos)) - 186);

          var bg_css = 'center ' + yPos + 'px';

          $object.css({ "background-position": bg_css });
        } else {
          $object.css({ "background-position": "center" });
        }
      });
    };

    $(function () {
      // Hero Section - Background Parallax
      background_image_parallax($(".tm-parallax"), 0.30, false);
      background_image_parallax_2($("#contact"), 0.80);
      background_image_parallax_2($("#testimonials"), 0.80);

      // Handle window resize
      window.addEventListener('resize', function () {
        background_image_parallax($(".tm-parallax"), 0.30, true);
      }, true);

      // Detect window scroll and update navbar
      $(window).scroll(function (e) {
        if ($(document).scrollTop() > 120) {
          $('.tm-navbar').addClass("scroll");
        } else {
          $('.tm-navbar').removeClass("scroll");
        }
      });

      // Close mobile menu after click 
      $('#tmNav a').on('click', function () {
        $('.navbar-collapse').removeClass('show');
      })

      // Scroll to corresponding section with animation
      $('#tmNav').singlePageNav({
        'easing': 'easeInOutExpo',
        'speed': 600
      });

      // Add smooth scrolling to all links
      // https://www.w3schools.com/howto/howto_css_smooth_scroll.asp
      $("a").on('click', function (event) {
        if (this.hash !== "") {
          event.preventDefault();
          var hash = this.hash;

          $('html, body').animate({
            scrollTop: $(hash).offset().top
          }, 600, 'easeInOutExpo', function () {
            window.location.hash = hash;
          });
        } // End if
      });

      // Pop up
      $('.tm-gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        gallery: { enabled: true }
      });

      $('.tm-testimonials-carousel').slick({
        dots: true,
        prevArrow: false,
        nextArrow: false,
        infinite: false,
        slidesToShow: 3,
        slidesToScroll: 1,
        responsive: [
          {
            breakpoint: 992,
            settings: {
              slidesToShow: 2
            }
          },
          {
            breakpoint: 768,
            settings: {
              slidesToShow: 2
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1
            }
          }
        ]
      });

      // Gallery
      $('.tm-gallery').slick({
        dots: true,
        infinite: false,
        slidesToShow: 5,
        slidesToScroll: 2,
        responsive: [
          {
            breakpoint: 1199,
            settings: {
              slidesToShow: 4,
              slidesToScroll: 2
            }
          },
          {
            breakpoint: 991,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 2
            }
          },
          {
            breakpoint: 767,
            settings: {
              slidesToShow: 2,
              slidesToScroll: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          }
        ]
      });
    });
  </script>

</body>

</html>